---
- name: Initial server setup
  hosts: machines
  remote_user: ubuntu
  vars:
    ssh_public_key: ""
  tasks:
    - name: Add an SSH authorized public key
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', ssh_public_key) }}"
        state: present
    - name: Add kali apt signing key
      become: yes
      apt_key:
        url: https://archive.kali.org/archive-key.asc
        state: present
    - name: Add kali repository
      become: yes
      apt_repository:
        repo: "deb http://http.kali.org/kali kali-rolling main non-free contrib"
        state: present
    - name: Update and upgrade apt packages
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install required packages
      become: yes
      apt:
        name:
          - build-essential
          - ca-certificates
          - libpq-dev
          - apt-utils
          - apt-transport-https
          - python3-dev
          - python3-venv
          - curl
          - jq
          - vim
          - iptables-persistent
          - net-tools
          - tmux
          - whois
          - zip
          - unzip
