---
- name: Install git server
  hosts: machines
  remote_user: ubuntu
  vars:
    git_ssh_public_key: ""
  vars_prompt:
    - name: git_user_password
      prompt: "Type git user password"
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install required packages
      become: yes
      apt:
        name:
          - git
    - name: Add git user
      become: yes
      user:
        name: git
        password: "{{ git_user_password | password_hash('sha512') }}"
        shell: /usr/bin/git-shell
    - name: Create .ssh repo for git user
      become: yes
      become_user: git
      file:
        path: /home/git/.ssh
        state: directory
        mode: 0700
    - name: Add git SSH authorized public key
      become: yes
      become_user: git
      authorized_key:
        user: git
        key: "{{ lookup('file', git_ssh_public_key) }}"
        state: present
    - name: Prepare git repository
      become: yes
      file:
        path: /srv/git
        state: directory
        owner: git
        group: git
        mode: 0700
    - name: Dissalow ssh forwarding for git user
      become: yes
      replace:
        path: /home/git/.ssh/authorized_keys
        regexp: 'ssh-rsa'
        replace: 'no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa'
